summerproject/movie_sys/urls.py
from django.urls import path
from . import views
from .views import (
    MovieListView, MovieDetailView, BookingDetailView,
    MovieCreateView, MovieUpdateView,
    MovieDeleteView, OttCreateView, OttDetailView, OttListView, TheaterCreateView, MoviecollListView, process_bookings,
    MovieDetailView2, MovieDetailView3, process_bookings2, process_bookings3, TrailerView)


urlpatterns = [
    # path('', views.home, name='movie_sys-home'),
    path('', MovieListView.as_view(), name='movie_sys-home'),
    path('about/', views.about, name='movie_sys-about'),
    # path('occupied/',occupiedSeats,name="occupied_seat"),

    path('movie_coll/<int:theater_id>/movies/', MoviecollListView.as_view(), name='movie_sys-movie_coll'),
    path('movie_detail/<int:pk>/',MovieDetailView.as_view(), name='movie_detail'),
    path('movie_detail_2/<int:pk>/',MovieDetailView2.as_view(), name='movie_detail_2'),
    path('movie_detail_3/<int:pk>/',MovieDetailView3.as_view(), name='movie_detail_3'),
    path('trailer/<int:pk>/',TrailerView.as_view(), name='Trailerpage'),
    path('movie/new/', MovieCreateView.as_view(), name='movie-create'),
    path('movie/<int:pk>/update/', MovieUpdateView.as_view(), name='movie-update'),
    path('movie/<int:pk>/delete/', MovieDeleteView.as_view(), name='movie-delete'),

    path("ott/collection/",OttListView.as_view(),name='movie_sys-ott_collection'),
    path('ott/<int:pk>/', OttDetailView.as_view(), name='ott_detail'),
    path('ott/new/', OttCreateView.as_view(), name='ott-create'),
    path('my-booking/', views.my_booking, name='my_booking'),
    path('ott/<int:pk>/add_watch_later/', views.add_to_watch_later, name='add_watch_later'),

    path('theater/new/', TheaterCreateView.as_view(), name='theater-create'),
    path('movie/new/<int:user_id>/', MovieCreateView.as_view(), name='movie-create'),

    # path('occupied/', views.occupiedSeats, name='occupied_seats'),
    path('movie_detail/<int:pk>/process_bookings/', process_bookings, name='process_bookings'),
    path('movie_detail_2/<int:pk>/process_bookings2/', process_bookings2, name='process_bookings2'),
    path('movie_detail_3/<int:pk>/process_bookings3/', process_bookings3, name='process_bookings3'),
    path('search/', views.search_theater, name='search_theater'),
    path('cancel_booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    path('remove_watch_later/<int:pk>/', views.remove_from_watch_later, name='remove_watch_later'),
]

summerproject/summerproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf.urls.static import static
from users import views as user_views

from users.forms import UserUpdateView
from users import views
from django.conf import settings

from users.views import RegistrationrequestsView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('movie_sys.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path("login/",views.login,name="login"),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('movie_sys.urls')),

    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('search_user/',views.search,name='search'),
    # path('jet/', include('jet.urls', 'jet')),
    # path('dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('registration-requests/', RegistrationrequestsView.as_view(), name='registration_requests'),
    path('approve-registration/<int:request_id>/', views.approve_registration, name='approve_registration'),
    path('reject-registration/<int:request_id>/', views.reject_registration, name='reject_registration'),

]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

summerproject/movie_sys/models.py
from datetime import time, datetime

from PIL.Image import Image
from django.core.validators import MinValueValidator
from django.db import models
from django_resized import ResizedImageField
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
import datetime

# Create your models here.

class Theater(models.Model):
    theater_name = models.CharField(max_length=50, null=True)
    location = models.CharField(max_length=50, null=True)
    logo = ResizedImageField(size=[400, 400], quality=100, upload_to='theater_logos', default='default.jpg')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    no_of_seat_rows = models.IntegerField(default=10)
    num_of_seats_column = models.IntegerField(default=10)
    created_at = models.DateTimeField(auto_now_add=True)
    contact = models.IntegerField(default=9807654321, blank=False,null=False)

    class Meta:
        unique_together = ('theater_name', 'location')

    def __str__(self):
        return self.theater_name


class Movie(models.Model):
    # id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, null=False)
    poster = models.ImageField(default="default.jpg", upload_to='movie_poster')
    trailer_video = models.FileField(default="404Error.png",upload_to='movie_trailer_video/',null=True,blank=True)
    releasing_date = models.DateField( null=True,blank=True)
    screening_datetime = models.DateTimeField(
        default=timezone.localtime(timezone.now()).replace(hour=13, minute=0, second=0, microsecond=0))
    screening_datetime2 = models.DateTimeField(null=True,blank=True)
    screening_datetime3 = models.DateTimeField(null=True,blank=True)
    genre = models.CharField(max_length=50, null=True)
    cast = models.CharField(max_length=200, null=True)
    directed_by = models.CharField(max_length=50, null=True)
    theater = models.ForeignKey(Theater, on_delete=models.CASCADE, null=False, related_name='movies')
    description = models.CharField(max_length=500, null=True)
    # booked_seats = models.ManyToManyField('Booking', blank=True)
    promo_code = models.CharField(max_length=50, blank=True, null=True)
    offer = models.DecimalField(max_digits=5, decimal_places=2, null=True,blank=True)
    ticket_price = models.IntegerField(validators=[MinValueValidator(1)], default=1)
    reserved_seats = models.JSONField(blank=True, null=True)
    # ... other fields and methods ...

    def reserve_seat(self, row, col):
        if self.reserved_seats is None:
            self.reserved_seats = []
        self.reserved_seats.append((row, col))
        self.save()
    def get_reserved_seats(self):
        return self.reserved_seats if self.reserved_seats else []
    def get_formatted_screening_time(self):
        return self.screening_time.strftime("%H:%M")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.id:
            try:
                last_movie = Movie.objects.latest('id')
                self.id = last_movie.id + 1
            except Movie.DoesNotExist:
                self.id = 1
        super().save(*args, **kwargs)


class Upcomming(models.Model):
    title = models.CharField(max_length=50, null=False)
    poster = models.ImageField(default="default.jpg", upload_to='upcomming_poster')
    genre = models.CharField(max_length=50, null=True)
    cast = models.CharField(max_length=200, null=True)
    directed_by = models.CharField(max_length=50, null=True)
    upload_by = models.ForeignKey(Theater, on_delete=models.CASCADE, null=True, related_name='upcoming_movies')

    def save(self, *args, **kwargs):
        if not self.pk:  # object is being created
            self.upload_by = self._meta.model.upload_by.field.related_model.objects.get(
                pk=1)  # replace 1 with the id of the desired user
        super().save(*args, **kwargs)



class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    purchase_time = models.DateTimeField(auto_now_add=True, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default=1)
    seat_row = models.CharField(max_length=10, default=0)
    seat_column = models.CharField(max_length=1, default=0)
    is_booked = models.BooleanField(default=False)
    version = models.IntegerField(default=0)
    selected_screening = models.DateTimeField(null=True)
    is_canceled = models.BooleanField(default=False)

    class Meta:
        unique_together = ('movie', 'seat_row', 'seat_column')

    def __str__(self):
        return f"Booking {self.movie.title} - Seat {self.seat_row}-{self.seat_column}"

class Booking2(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    purchase_time = models.DateTimeField(auto_now_add=True, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default=1)
    seat_row = models.CharField(max_length=10, default=0)
    seat_column = models.CharField(max_length=1, default=0)
    is_booked = models.BooleanField(default=False)
    version = models.IntegerField(default=0)
    selected_screening = models.DateTimeField(null=True)
    is_canceled = models.BooleanField(default=False)

    class Meta:
        unique_together = ('movie', 'seat_row', 'seat_column')

    def __str__(self):
        return f"Booking for 2nd {self.movie.title} - Seat {self.seat_row}-{self.seat_column}"


class Booking3(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    purchase_time = models.DateTimeField(auto_now_add=True, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, default=1)
    seat_row = models.CharField(max_length=10, default=0)
    seat_column = models.CharField(max_length=1, default=0)
    is_booked = models.BooleanField(default=False)
    version = models.IntegerField(default=0)
    selected_screening = models.DateTimeField(null=True)
    is_canceled = models.BooleanField(default=False)

    class Meta:
        unique_together = ('movie', 'seat_row', 'seat_column')

    def __str__(self):
        return f"Booking for 3rd {self.movie.title} - Seat {self.seat_row}-{self.seat_column}"








class Ott(models.Model):
    title = models.CharField(max_length=50, null=False)
    poster = models.ImageField(default="default.jpg", upload_to='Ott_poster')
    genre = models.CharField(max_length=50, null=True, blank=True)
    cast = models.CharField(max_length=200, null=True, blank=True)
    description = models.CharField(max_length=500, blank=True)
    movie_video = models.FileField(upload_to='ott_movie_videos/', null=False)
    trailer_video = models.FileField(upload_to='ott_movie_trailer/', null=True, blank=True)
    upload_by = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('ott_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class WatchLater(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie_title = models.ForeignKey(Ott,on_delete=models.CASCADE)

def is_screening_time_passed(screening_time):
    current_time = datetime.now().time()
    return current_time > screening_time

summerproject/movie_sys/templates/movie_sys/about.html
{% extends "movie_sys/base.html" %}

{% block content %}
<h2>Hi this is about</h2>
<p>Welcome to our site, We have created an online platform to enhance your movie-going experience, allowing you to
    browse movies, select theaters, and purchase tickets all in one place. Our system is designed with you in mind,
    to provide an easy and efficient way for you to enjoy your favorite movies.

Our platform features a range of user types, including Guest Users, Registered Users, Admins, Managers, and Clients.
    Admins have access to manage other users and the Over The Top (OTT) content on the platform, while Managers manage
    theaters and showtimes. Clients are regular users who can browse movies, select theaters, purchase tickets, and
    leave reviews.

Our system offers a variety of advanced features such as user authentication, account management, and user login/logout
    options. Additionally, Admin users have access to User Management and OTT Management, while Manager users have
    access to Theater Management.

Our movie ticket system project is built with the aim of providing you with a seamless experience when buying movie tickets, while also allowing you to discover new films and share your opinions with others. So, sit back, relax, and enjoy your favorite movies with our movie ticket system project."</p>
<span>Rules and regulations</span>
<ul>
    <li>
            No outside food or drinks are allowed in the cinema hall.
    </li>
        <li>
  Smoking or use of any form of tobacco products is prohibited inside the cinema hall.
    </li>
        <li>
The cinema hall is not responsible for lost or stolen items.
    </li>
        <li>
Patrons are expected to behave in a courteous and respectful manner towards other patrons and cinema hall staff.
    </li>
        <li>
Patrons are expected to turn off or silence their mobile phones during the movie.
    </li>
        <li>
Latecomers will not be allowed into the cinema hall once the movie has started.
    </li>    <li>
In case of any emergency or need for assistance, patrons should contact the cinema hall staff immediately.
    </li>
        <li>
The cinema hall reserves the right to refuse entry to any patron or to ask any patron to leave if they violate any of the rules or behave in a disruptive manner.

    </li>
        <li>
Patrons are advised to follow the seating arrangements and not change seats once the movie has started.
    </li>
        <li>

Children under the age of 12 should be accompanied by an adult while watching movies in the cinema hall.
    </li>

    <li>

booked ticket must be reedem 1hr before the airing time otherwise it can be sold to other person.
    </li>
</ul>
{% endblock content %}

summerproject/movie_sys/templates/movie_sys/home.html
<!--PS E:\Summer_project\summerproject> python manage.py runserver-->

{% extends "movie_sys/base.html" %}

{% block title %} Home {% endblock %}
{% block content %}
<center><h2>Movie ticket booking</h2></center>

<div class="col-md-12 d-flex justify-content-end">
    <form method="get" class="form-inline my-2 my-lg-0" action="{% url 'search_theater' %}">
        <input type="search" class="form-control search_input mr-sm-2" name="query" placeholder="location..."
               value="{{ request.GET.query }}">
    </form>
</div>
<div class="gallery">
    <div class="row">
        {% for theater in theaters %}
        <div class="item col-md-3">
            <a href="{% url 'movie_sys-movie_coll' theater.id %}">
                <img src="{{ theater.logo.url }}" alt="{{ theater.name }}" width="300px" height="300px"></a>
            <div class="details" style="width: 100%;">
                <div class="text-center">
                    <h6 style="font-size: 20px">{{ theater.theater_name }}</h6>
                    <span class="bi bi-geo-alt">{{ theater.location }}</span>
                    <a href="{% url 'movie_sys-movie_coll' theater.id %}" class="btn btn-primary">Visit</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<hr>
<hr>
<div class="container">
    <h2 class="text-center my-5">Upcomming Movies</h2>
    <div class="gallery">
        {% for upcomming in upcommings %}
        <div class="upcomming_item">
            <img src="{{ upcomming.poster.url }}" alt="{{ upcomming.title }}" width="300px" height="400px">
            <div class="details">
                <h2 class="upcomming_head">{{ upcomming.title }}</h2>
                <p><strong>Genre:</strong> {{ upcomming.genre }}</p>
                <p><strong>Cast:</strong> {{ upcomming.cast }}</p>
                <p><strong>Directed By:</strong> {{ upcomming.directed_by }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<hr>
<hr>

<h2 class="text-center my-5">Browse Movies</h2>
<div class="gallery">
    <div class="row">
        {% for ott in ott_list %}
        <div class="item col-md-3">
            <a href="{% url 'ott_detail' pk=ott.pk %}">
                <img src="{{ ott.poster.url }}" alt="{{ theater.theater_name }}" width="300px" height="300px"></a>
            <div>
                   <a href="{% url 'add_watch_later' pk=ott.pk %}" class="btn btn-primary">Add watch later</a>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
<a href="{% url 'movie_sys-ott_collection' %}" class="btn btn-primary">Explore More</a>
<hr>


{% endblock %}

summerproject/movie_sys/templates/movie_sys/movie_coll.html
{% extends "movie_sys/base.html" %}

{% block title %} movie collection {% endblock %}

{% block content %}
<h1>Movies</h1>
<!--{% if user.is_authenticated %}-->
<!--    {% if user.profile.role == 'admin'%}-->
<!--        <a style="width:300px; align:left;" class="btn btn-secondary " href="{% url 'movie-create' %}">Add movie </a>-->
<!--    {% endif %}-->
<!--{% endif %}-->
{% if user.is_authenticated %}
    <p>Logged-in User: {{ user }}</p>
    <p>Theater Owner: {{ theater.user }}</p>
     {% if request.user == theater.user %}
        <a style="width:300px; align:left;" class="btn btn-secondary" href="{% url 'movie-create' user_id=theater.user.id %}">Add movie</a>
    {% endif %}
{% endif %}





<hr>
{% if movies %}
<div class="row">
    {% for movie in movies %}
    <div class="col-md-4">
        <div class="poster">
<hr><br>
            <a href="{% url 'Trailerpage' pk=movie.pk %}" ><img src="{{ movie.poster.url }}" alt="{{ movie.title }}" width="80%" height="250px"></a>
        </div>
    </div>
    <div class="col-md-5">
        <div class="detailss">
            <h2>{{ movie.title }}</h2>
            <p>{{ movie.description }}</p>
            <a href="{% url 'Trailerpage' pk=movie.pk %}"><span><i class="bi bi-camera-reels"></i>Trailer</span></a>

        </div>
    </div>
    <div class="col-md-2">
        <div class="info">
            <ul class="movie-meta">
                <li><strong>Director:</strong> {{ movie.directed_by }}</li>
                <li><strong>Genre:</strong> {{ movie.genre }}</li>
                <li><strong>Release Date:</strong> {{ movie.release_date }}</li>
            </ul>
            {% if request.user == movie.theater.user %}
    <!-- Only show the edit and delete buttons if the current user owns the theater -->
    <a href="{% url 'movie-update' movie.pk %}" class="btn btn-primary btn-sm">Edit</a>
    <a href="{% url 'movie-delete' movie.pk %}" class="btn btn-danger btn-sm">Delete</a>
{% endif %}

            <a href="{% url 'movie_detail' movie.pk %}" class="btn btn-success btn-sm">Visit</a>

        </div>
    </div>
    {% endfor %}
</div>
{% endif %}










































<hr>
<hr>
<h2>Upcoming Movies</h2>

{% if upcommings %}
<div class="row">
    {% for upcomming in upcommings %}
    <div class="col-md-4">
        <div class="cardd mb-3">
            <img src="{{ upcomming.poster.url }}" class="card-img-top" alt="{{ upcomming.title }}" width="200px"
                 height="500px">
            <div class="card-body">
                <h5 class="card-title">{{ upcomming.title }}</h5>
                <p class="card-text">{{ upcomming.description }}</p>
                <ul class="movie-meta">
                    <li><strong>Director:</strong> {{ upcomming.directed_by }}</li>
                    <li><strong>Genre:</strong> {{ upcomming.genre }}</li>
                </ul>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No upcoming movies found.</p>
{% endif %}


{% endblock content %}

summerproject/movie_sys/templates/movie_sys/movie_confirm_delete.html
{% extends "movie_sys/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Movie</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'movie_detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

summerproject/movie_sys/templates/movie_sys/movie_form.html
{% extends "movie_sys/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
                <button type="button" class="btn btn-danger btn-sm ml-2" id="goBackButton">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-arrow-left" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"></path>
                </svg>
                Go BACK
            </button>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">movie Post</legend>
            {{ form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Post</button>
        </div>
    </form>
</div>
{% endblock content %}

summerproject/movie_sys/templates/movie_sys/mybookings.html
{% extends "movie_sys/base.html" %}

{% block title %} Watch later {% endblock %}
{% block content %}

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                {% if message.tags %}
                <h4 class="msg {{ message.tags }} fs-3">
                    {% endif %}
                    {{ message }}
                </h4>
                {% endfor %}
            </ul>
            {% endif %}



<div class="container">
    <table class="table border rounded">
        <legend>Booked Seats</legend>
        <thead>
        <tr>
            <th scope="col">Movie name</th>
            <th scope="col">Genre</th>
            <th scope="col">Seat</th>
            <th scope="col">Purchase time</th>
            <th scope="col">screening date & time</th>
            <th scope="col">Cacel show</th>
        </tr>
        </thead>
        <tbody>

        {% for booking in all_bookings %}
        <tr class="table-active">
            <td>{{ booking.movie }}</td>
            <td>{{ booking.movie.genre }}</td>
            <td>{{ booking.seat_row }}{{ booking.seat_column }}</td>
            <td>{{ booking.purchase_time }}</td>
            <td>{{ booking.selected_screening }}</td>
            <td>
                {% if not booking.canceled %}
                <a href="{% url 'cancel_booking' booking.id %}">
                    <span class="btn btn-outline-danger bi bi-trash">Cancel</span>
                </a>
                {% else %}
                <p>Canceled</p>
                {% endif %}
            </td>
        </tr>
        {% endfor %}


        </tbody>
    </table>

</div>

<center>
    <h2>Watch Later OTT Movies:</h2>
</center>
<!--<ul>-->
<!--    {% for ott in watch_later_ott %}-->
<!--    <li><a href="{% url 'ott_detail' pk=ott.pk %}">{{ ott.title }}</a></li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<div class="container col-md-8">
    <table class="table border rounded">
        <legend>Watch now than later:</legend>
        <thead>
        <tr>
            <th scope="col">Movie name</th>
            <th scope="col">Genre</th>
            <th scope="col">Watch now</th>
            <th scope="col">remove</th>
        </tr>
        </thead>
        <tbody>

        {% for ott in watch_later_ott %}
        <tr class="table-active">
            <td>{{ ott.title }}</td>
            <td>{{ ott.genre }}</td>
            <td><a class="btn btn-sm btn-primary" href="{% url 'ott_detail' pk=ott.pk %}">Play</a></td>
            <td>
                <a href="{% url 'remove_watch_later' pk=ott.pk %}">
                    <span class="btn btn-sm btn-outline-danger bi bi-trash">Remove</span>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

{% endblock %}

summerproject/movie_sys/templates/movie_sys/ott_coll.html
{% extends 'movie_sys/base.html'%}

{% block content %}
{% if user.is_authenticated %}
{% if user.profile.role == 'admin'%}
<a style="width:300px; align:left;" class="btn btn-secondary " href="{% url 'ott-create' %}">Add OTT movie </a>
{% endif %}
{% endif %}
{% if ott_list %}
<div class="row">
    {% for ott in ott_list %}
    <div class="col-md-2 ott_mov" style="border: 1px solid white;">
        <!--<a href="{% url 'ott_detail' pk=ott.pk %}">-->
        <a href="{% url 'ott_detail' pk=ott.pk %}">
            <img src="{{ ott.poster.url }}" alt="{{ ott.title }}" width="200px" height="250px">
            <h2 style="font-size:25px;">{{ ott.title }}</h2>
            <p>{{ ott.description }}</p>
        </a>
        <div>
            <a href="{% url 'add_watch_later' pk=ott.pk %}" class="btn btn-primary">Add watch later</a>
        </div>
    </div>

    {% endfor %}
    {% if is_paginated %}

    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

    {% endif %}

</div>
{% endif %}
{% endblock content %}